theme = "onedark"

[editor]
true-color = true
line-number = "relative"
bufferline = "multiple"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "|" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["version-control"]
right = ["diagnostics", "file-type", "selections","register", "position", "file-encoding"]

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
tab = "all"

[keys.normal]
C-b = ":bc!"

[keys.normal.space]
l = [
  ":sh echo \"%{buffer_name}:%{selection_line_start}-%{selection_line_end}\" | tmux load-buffer -",
]
t = [
  ":insert-output \"grep %{buffer_name} -e 'TODO' -Hn || echo 'No TODOs found'\"",
  "delete_selection",
  ":n",
  "paste_after"
]
T = [
  ":n",
  ":insert-output \"git grep -n TODO || echo 'No TODOs found'\"",
  "delete_selection",
  "paste_after"
]
m = [
  ":o .clangd",
  "select_all",
  "delete_selection",
  ":insert-output \"echo 'CompileFlags:'\"",
  "open_below",
  ":insert-output \"echo '    Add: ['\"",
  "goto_line_end_newline",
  ":insert-output \"printf 'inspect:\\n\\t@echo \\$(CFLAGS)\\n' | make -f Makefile -f - inspect | sed -E 's/[[:space:]]+/, /g'\"",
  "goto_line_end_newline",
  ":insert-output \"echo ]\"",
  ":w",
  ":bc",
  "normal_mode"
]
M = [
  ":o .clangd",
  "select_all",
  "delete_selection",
  ":insert-output \"echo 'CompileFlags:'\"",
  "open_below",
  ":insert-output \"echo '    Add: ['\"",
  "goto_line_end_newline",
  ":insert-output \"printf 'inspect:\\n\\t@echo \\$(CPPFLAGS)\\n' | make -f Makefile -f - inspect | sed -E 's/[[:space:]]+/, /g'\"",
  "goto_line_end_newline",
  ":insert-output \"echo ]\"",
  ":w",
  ":bc",
  "normal_mode"
]

[keys.insert]
C-t = "@<esc>bc<S-lt><space><esc>h<S-R>li<S-gt><ret><S-lt>/<space><esc>h<S-R>li<S-gt><esc>kglli<ret>"
C-y = "@<esc>bc<S-lt><space><esc>h<S-R>li<S-gt><S-lt>/<space><esc>h<S-R>li<S-gt><esc>F<S-lt>i"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
