[[language]]
name = "rust"
indent = { tab-width = 4, unit = "    " }

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}" }

[[language]]
name = "python"
indent = { tab-width = 4, unit = "    " }
language-servers = [
  {name = "ruff", except-features = ["hover"]},
  "basedpyright"
]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
# I find the python formatters a bit too strict and opinionated
# so I prefer formatting selections with '=' when needed
auto-format = false

[language-server.basedpyright.config.python.analysis]
# Disable specific diagnostics that Ruff already handles
diagnosticSeverityOverrides = { reportUnusedImport = "none", reportUnusedVariable = "none", reportDuplicateImport = "none" }
typeCheckingMode = "standard"
autoImportCompletions = true
diagnosticMode = "workspace"

[[language]]
name = "haskell"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}" }

[language-server.clangd-cpp]
command = "clangd"
args = ["--header-insertion=never"]

[[language]]
name = "cpp"
file-types = ["cc", "hh", "c++", "cpp", "hpp", "h", "ipp", "tpp", "cxx", "hxx", "ixx", "txx", "ino", "cu", "cuh", "cppm", "h++", "ii", "inl", { glob = ".hpp.in" }, { glob = ".h.in" }]
language-servers = ["clangd-cpp"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "bash"
file-types = [
  "sh",
  "bash",
  "ash",
  "dash",
  "ksh",
  "mksh",
  "zsh",
  "zshenv",
  "zlogin",
  "zlogout",
  "zprofile",
  "zshrc",
  "eclass",
  "ebuild",
  "bazelrc",
  "Renviron",
  "zsh-theme",
  "cshrc",
  "tcshrc",
  "bashrc_Apple_Terminal",
  "zshrc_Apple_Terminal",
  { glob = "i3/config" },
  { glob = "sway/config" },
  { glob = ".tmux.conf" },
  { glob = "tmux.conf" },
  { glob = ".bash_history" },
  { glob = ".bash_login" },
  { glob = ".bash_logout" },
  { glob = ".bash_profile" },
  { glob = ".bashrc" },
  { glob = ".profile" },
  { glob = ".zshenv" },
  { glob = ".zlogin" },
  { glob = ".zlogout" },
  { glob = ".zprofile" },
  { glob = ".zshrc" },
  { glob = ".zimrc" },
  { glob = "APKBUILD" },
  { glob = ".bash_aliases" },
  { glob = ".Renviron" },
  { glob = ".xprofile" },
  { glob = ".xsession" },
  { glob = ".xsessionrc" },
  { glob = ".yashrc" },
  { glob = ".yash_profile" },
  { glob = ".hushlogin" },
]

[[language]]
name = "c-sharp"
indent = { tab-width = 4, unit = "    " }
language-servers = [
    # { name = "roslyn-language-server", except-features = ["diagnostics"] },
    { name = "roslyn-language-server" },
    # { name = "csharp-ls", only-features = ["diagnostics"] }
    # { name = "csharp-ls"}
]

[language-server.roslyn-language-server]
command = "roslyn-language-server"
args = ["--stdio", "--autoLoadProjects"]

[language-server.csharp-ls]
command = "csharp-ls"

[[language]]
name = "grammar-check"
language-id = "plaintext"
scope = "source.harper"
file-types = ["harper"]
roots = []
language-servers = ["harper-ls"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls]
