HISTSIZE=5000
SAVEHIST=5000
HISTFILE=~/.zsh_history
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt PROMPT_SUBST

git_branch() {
  local branch
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
    [[ -n $branch ]] && printf '(%s)' "$branch"
  fi
}

# Prompt colors using zsh's %F{...} (set color) and %f (reset)
# %n = username, %~ = current dir (with ~), $(git_branch) evaluated by PROMPT_SUBST
PROMPT='%F{green}%n %F{magenta}%~ %F{blue}$(git_branch)%f
%F{green}$ %f'

# Configure LSCOLORS
export CLI_COLOR=1
# (Theme generated by Gemini 3)
# Ex: Directories -> Bold Blue
# Fx: Symlinks    -> Bold Magenta
# cx: Sockets     -> Green
# dx: Pipes       -> Yellow
# Bx: Executables -> Bold Red
# Dx: Block/Char  -> Bold Yellow
# Cx: Setuid      -> Bold Green
# Gx: Setgid      -> Bold Cyan
# x:  Backgrounds -> None (Transparent/Default)
export LSCOLORS="ExFxcxdxBxDxDxCxGxexex"

# Configure zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8,bold"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=45
ZSH_AUTOSUGGEST_HISTORY_IGNORE="git clone *"
ZSH_AUTOSUGGEST_COMPLETION_IGNORE="git clone *"

# add extra completion data stored in ~/.zfunc
fpath+=~/.zfunc

# make sure compinit is called
autoload -U compinit && compinit
_fix_cursor() {
  printf '\033[5 q'
}
precmd_functions+=(_fix_cursor)
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
