HISTSIZE=5000
SAVEHIST=5000
HISTFILE=~/.zsh_history
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt PROMPT_SUBST

git_branch() {
  local branch
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
    [[ -n $branch ]] && printf '(%s)' "$branch"
  fi
}

# Prompt colors using zsh's %F{...} (set color) and %f (reset)
# %n = username, %~ = current dir (with ~), $(git_branch) evaluated by PROMPT_SUBST
PROMPT='%F{green}%n %F{magenta}%~ %F{blue}$(git_branch)%f
%F{green}$ %f'

export CHROME_EXECUTABLE=/usr/bin/chromium

# Configure LSCOLORS
export CLI_COLOR=1
# (Theme generated by Gemini 3)
# Ex: Directories -> Bold Blue
# Fx: Symlinks    -> Bold Magenta
# cx: Sockets     -> Green
# dx: Pipes       -> Yellow
# Bx: Executables -> Bold Red
# Dx: Block/Char  -> Bold Yellow
# Cx: Setuid      -> Bold Green
# Gx: Setgid      -> Bold Cyan
# x:  Backgrounds -> None (Transparent/Default)
export LSCOLORS="ExFxcxdxBxDxDxCxGxexex"

# Modified from https://github.com/Discomanfulanito/pokefetch/
if [ -f "$HOME/.poke_sprite" ]; then
  poke_sprite=$(cat "$HOME/.poke_sprite")
else
  poke_sprite=$(pokeget shedinja --hide-name)
  echo "$poke_sprite" > "$HOME/.poke_sprite"
fi
ff_lines=$(fastfetch --logo none | wc -l)
sp_lines=$(echo "$poke_sprite" | wc -l)
poke_sprite_pad_top=$(( (ff_lines - sp_lines) / 2 + 2 ))
poke_sprite_pad_top=$(( poke_sprite_pad_top < 0 ? 0 : poke_sprite_pad_top ))
poke_sprite_width=$(printf "%s\n" "$poke_sprite" | sed $'s/\e\\[[0-9;]*m//g' | awk '{ if (length > max) max = length } END { print max+0 }')
poke_sprite_pad_left=$(( (38 - poke_sprite_width) / 2 ))
poke_sprite_pad_left=$(( poke_sprite_pad_left < 0 ? 0 : poke_sprite_pad_left ))
poke_sprite_pad_left=$(( poke_sprite_pad_left + 1 ))
poke_sprite_pad_right=$(( (38 - poke_sprite_width + 1) / 2 ))
poke_sprite_pad_right=$(( poke_sprite_pad_right < 0 ? 0 : poke_sprite_pad_right ))
poke_sprite_pad_right=$(( poke_sprite_pad_right + 1 ))
fetch() {
  echo "$poke_sprite" | fastfetch --file-raw - \
    --logo-padding-top "$poke_sprite_pad_top" \
    --logo-padding-left "$poke_sprite_pad_left" \
    --logo-padding-right "$poke_sprite_pad_right"
}
# Configure zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8,bold"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=45
ZSH_AUTOSUGGEST_HISTORY_IGNORE="git clone *"
ZSH_AUTOSUGGEST_COMPLETION_IGNORE="git clone *"

# add extra completion data stored in ~/.zfunc
fpath+=~/.zfunc

# make sure compinit is called
autoload -U compinit && compinit
_fix_cursor() {
  printf '\033[5 q'
}
precmd_functions+=(_fix_cursor)
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
