# Path stuff
. "$HOME/.cargo/env"
export PATH="$HOME/bin/:$PATH"
export PATH="/usr/local/go/bin/:$PATH"
export GOPATH="$HOME/go/"
export PATH="$GOPATH/bin/:$PATH"
export LC_RPATH="/usr/local/lib/"

# Editor
export EDITOR="hx"

# Make sure TERM supports colors
export TERM=${TERM:-xterm-256color}

# Configure LSCOLORS
export CLI_COLOR=1
# (Theme generated by Gemini 3)
# Ex: Directories -> Bold Blue
# Fx: Symlinks    -> Bold Magenta
# cx: Sockets     -> Green
# dx: Pipes       -> Yellow
# Bx: Executables -> Bold Red
# Dx: Block/Char  -> Bold Yellow
# Cx: Setuid      -> Bold Green
# Gx: Setgid      -> Bold Cyan
# x:  Backgrounds -> None (Transparent/Default)
export LSCOLORS="ExFxcxdxBxDxDxCxGxexex"

# Alias the custom extra colored `lsc` function to `ls`
export ALIAS_LSC="yes"

# Configure zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8,bold"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_HISTORY_IGNORE="git clone *"
ZSH_AUTOSUGGEST_COMPLETION_IGNORE="git clone *"

# Aliases
alias hx="_hx" # defined in .zshrc
alias lg='lazygit'
alias cls="clear"
alias ls="ls -Alh --color=yes"
alias wd="cd \$(walked $HOME/.config/walked/walked.toml)"
alias rc="printf '\033[5 q'"
