HISTSIZE=5000
SAVEHIST=5000
HISTFILE=~/.zsh_history
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt PROMPT_SUBST

git_branch() {
  local branch
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
    [[ -n $branch ]] && printf '(%s)' "$branch"
  fi
}

# Prompt colors using zsh's %F{...} (set color) and %f (reset)
# %n = username, %~ = current dir (with ~), $(git_branch) evaluated by PROMPT_SUBST
PROMPT='%F{green}%n %F{magenta}%~ %F{blue}$(git_branch)%f
%F{green}$ %f'

# Configure LSCOLORS
export CLI_COLOR=1
# (Theme generated by Gemini 3)
# Ex: Directories -> Bold Blue
# Fx: Symlinks    -> Bold Magenta
# cx: Sockets     -> Green
# dx: Pipes       -> Yellow
# Bx: Executables -> Bold Red
# Dx: Block/Char  -> Bold Yellow
# Cx: Setuid      -> Bold Green
# Gx: Setgid      -> Bold Cyan
# x:  Backgrounds -> None (Transparent/Default)
export LSCOLORS="ExFxcxdxBxDxDxCxGxexex"

# Custom extra colored `ls`
lsc() {
  local ESC=$'\e'
  local COLOR1="${ESC}[1;31m" # bold red
  local COLOR2="${ESC}[32m"   # green
  local COLOR3="${ESC}[33m"   # yellow
  local COLOR4="${ESC}[34m"   # blue
  local RESET="${ESC}[0m"

  # yeah we parse the entire `ls` output again each time womp womp
  ls "$@" | while read -r line; do
    local perms="${line:0:11}"
    local rest="${line:11}"

    local colored_perms="${perms//x/${COLOR1}x${RESET}}"
    local colored_perms="${colored_perms//w/${COLOR2}w${RESET}}"
    local colored_perms="${colored_perms//r/${COLOR4}r${RESET}}"
    local colored_perms="${colored_perms//s/${COLOR3}s${RESET}}"
    local colored_perms="${colored_perms//S/${COLOR3}S${RESET}}"
    
    print -r -- "${colored_perms}${rest}"
  done
}

# Alias the custom extra colored `lsc` function to `ls`
export ALIAS_LSC="yes"

# if the overhead becomes a problem for some reason, add toggle for aliasing
if [[ "$ALIAS_LSC" == "yes" ]]; then
  alias ls="lsc"
fi

# Cache brew prefix
__BREW_PREFIX=$(brew --prefix)

# Alias watch utility
_watch() {
  $__BREW_PREFIX/bin/watch -c -t -x env RC_ON_LOGIN="no" zsh -lic -b "$@"
}
alias watch="_watch"

# Hack because my cursor gets stuck as a block shape after I exit helix
_hx() {
  $__BREW_PREFIX/bin/hx "$@"
  printf '\033[5 q'
}
alias hx="_hx"

# Configure zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8,bold"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=45
ZSH_AUTOSUGGEST_HISTORY_IGNORE="git clone *"
ZSH_AUTOSUGGEST_COMPLETION_IGNORE="git clone *"

# add extra completion data stored in ~/.zfunc
fpath+=~/.zfunc

# make sure compinit is called
autoload -U compinit && compinit

# source zsh-autosuggestions
source $__BREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# reset cursor to bar unless instructed otherwise
if [[ "$RC_ON_LOGIN" != "no" ]]; then
  rc
fi
